# This is a basic workflow to help you get started with Actions

name: Report Codecov

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Generate report
        run: gradle clean codeCoverageReport

      - name: Upload coverage reports
        uses: codecov/codecov-action@v1
        with:
          files: ./build/reports/jacoco/report.xml
